<package format="3">
  <name>tmc_potential_maps</name>
  <version>3.0.0</version>
  <description>Store the entity of the potential map</description>
  <maintainer email="xr-hsr-support@mail.toyota.co.jp">HSR Support</maintainer>

  <license>BSD 3-clause Clear License</license>

  <url type="website" />


  <author>Yumiko Ikeda</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>